In [2]:
import numpy as np

In [14]:
array_1=np.array([[1,2],[3,4]])
array_2=np.array([5,6])
print(array_1)
print("X")
print(array_1)

# np.dot(array_1,array_1)
print(np.dot(array_2,array_2))

[[1 2]
 [3 4]]
X
[[1 2]
 [3 4]]
61


In [17]:
# np.linalg.multi_dot()
from numpy import linalg as la

array_1=np.array([[1,2],[3,4]])
array_2=np.array([5,6])
print(array_1)
print("X")
print(array_1)
print("X")
print(array_2)

la.multi_dot([array_1,array_1,array_2])  #used to multiply the multiple matrices 

[[1 2]
 [3 4]]
X
[[1 2]
 [3 4]]
X
[5 6]


array([ 95, 207])

In [20]:
np.inner(array_1,array_1)   # performs calculation like: a1*b1+a2*b2 (row-row) multiplication of matrices

array([[ 5, 11],
       [11, 25]])

In [22]:
la.matrix_power(array_1,2)  #matrix is multiplied with itself if power=2 then A²=A*A

array([[ 7, 10],
       [15, 22]])

In [29]:
la.inv(array_1)     # A-¹ = AdjA / |A|


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [39]:
# Task:
A= np.array([[14,-7],[9,12]])
B= np.array([[6],[-9]])

print(A)
print("============")
print(B)
print("============")

inverseA=la.inv(A)
A_dot_B=np.dot(A,B)
A_power_4=la.matrix_power(A,4)
print("=====Inverse of A matrix=======")
print(inverseA)
print("======Dot Product of A and B: (A.B)======")
print(A_dot_B)
print("=====A power 4=======")
print(A_power_4)

[[14 -7]
 [ 9 12]]
[[ 6]
 [-9]]
=====Inverse of A matrix=======
[[ 0.05194805  0.03030303]
 [-0.03896104  0.06060606]]
======Dot Product of A and B (A.B)======
[[147]
 [-54]]
=====A power 4=======
[[-24899 -38948]
 [ 50076 -36027]]


In [42]:
la.det(A) # to calculate the determinant of matrix
la.norm(A) # to calculate the norm form of matrix

21.6794833886788

In [47]:
from numpy import genfromtxt
#first way to load the csv file
house_price=genfromtxt("housing_price_dataset.csv",delimiter=",")  #doesn't give the headers of csv as an output (Here: Strings are considered as None values)
house_price
# another way to load the csv file
my_file=np.loadtxt("housing_price_dataset.csv",delimiter=",", dtype=object) #dtype: consider all the values as an string
my_file

array([['SquareFeet', 'Bedrooms', 'Bathrooms', 'Neighborhood',
        'YearBuilt', 'Price'],
       ['2126', '4', '1', 'Rural', '1969', '215355.28361820139'],
       ['2459', '3', '2', 'Rural', '1980', '195014.22162584803'],
       ...,
       ['2979', '5', '3', 'Suburb', '1962', '384110.55559035065'],
       ['2596', '5', '2', 'Rural', '1984', '380512.68595683837'],
       ['1572', '5', '3', 'Rural', '2011', '221618.58321806978']],
      dtype=object)

In [ ]:
features=my_file[0] #stores all the headers from the file (Not useful for performing calculations)
features

In [54]:
my_file = np.delete(my_file,0,axis=0)   # to delete the headers from the csv


In [55]:
my_file.shape  # to count the total number of rows present in our dataset

(49999, 6)

In [49]:
my_file=np.where(my_file=='', '0',my_file) #where is used to provide default values like: '0' is the default value for any column having the null value

In [51]:
my_file[my_file=='0']  #returns where the null values present in the complete dataset

array([], dtype=object)

In [64]:
prices= my_file[:,5].astype(float)  #returns the complete price column 
print("Average value: ",np.average(prices))
print("Mean value:",np.mean(prices))  
print("Standard deviation: ",np.std(prices)) #standard deviation: diff between mean point and end point 
print("Variance:",np.var(prices)) 

Average value:  224827.51459560997
Mean value: 224827.51459560997
Standard deviation:  76141.83118235963
Variance: 5797578455.802954


In [70]:
array=np.array([4,6,3,5,2])
print(np.average(array))
print(np.mean(array))
print(np.var(array))
print(np.std(array))

4.0
4.0
2.0
1.4142135623730951
