### Task: Generate random list of 10/10 from 0-10.
#### Make 10/10 matrix multiply it by 3 and separate even and odd numbers and make 2 by m matrices.

In [1]:
import numpy as np

# Step#01: Generate a 10x10 matrix of random integers from 0 to 9, then multiply by 3
random_numbers=np.random.randint(0,10, size=(10,10))*3
print(random_numbers)

[[24 21  0 15  3 18 12 21 24  3]
 [ 6  3  6  6  3  6 27 27 18 27]
 [12 18  6 15 18  3 15  6 24  0]
 [15 15  9 15 27 12 24  9 24 21]
 [ 6  3  6 21 18  6 12 27 27 18]
 [ 9  9 27 24 24 12 18 12  9 21]
 [18  3  6 24  9 15 15 21 27 27]
 [ 9 15  6  0  3 12 21 18 24 12]
 [15 18 15  9 18  0 21 21 15  9]
 [15 27  3 12 15  9 18 12  6  9]]


In [2]:
evens= random_numbers[random_numbers%2==0]
print(evens)

[24  0 18 12 24  6  6  6  6 18 12 18  6 18  6 24  0 12 24 24  6  6 18  6
 12 18 24 24 12 18 12 18  6 24  6  0 12 18 24 12 18 18  0 12 18 12  6]


In [3]:
odds= random_numbers[random_numbers%2!=0]
print(odds)

[21 15  3 21  3  3  3 27 27 27 15  3 15 15 15  9 15 27  9 21  3 21 27 27
  9  9 27  9 21  3  9 15 15 21 27 27  9 15  3 21 15 15  9 21 21 15  9 15
 27  3 15  9  9]


In [4]:
# Ensure each array can be reshaped into 2xm by trimming last element if needed
if evens.size%2!=0:
    evens=evens[:-1]
if odds.size%2!=0:
    odds=odds[:-1]

In [5]:
# Reshape into 2xm matrices
evens_2xm=evens.reshape(2,-1)
print(evens_2xm)

[[24  0 18 12 24  6  6  6  6 18 12 18  6 18  6 24  0 12 24 24  6  6 18]
 [ 6 12 18 24 24 12 18 12 18  6 24  6  0 12 18 24 12 18 18  0 12 18 12]]


In [6]:
# Reshape into 2xm matrices
odds_2xm=odds.reshape(2,-1)
print(odds_2xm)

[[21 15  3 21  3  3  3 27 27 27 15  3 15 15 15  9 15 27  9 21  3 21 27 27
   9  9]
 [27  9 21  3  9 15 15 21 27 27  9 15  3 21 15 15  9 21 21 15  9 15 27  3
  15  9]]
