In [ ]:
""" 
Basic Array Tasks
    Create a 1D array of numbers from 0 to 9.
    Create a 3x3 array of all zeros and another of all ones 
    Generate a 4x4 identity matrix.
    Create an array of 10 linearly spaced values between 0 and 5.
Array operations
    Perform element-wise addition, subtraction, and multiplication on two arrays.
    Calculate the sum, mean, standard deviation, and max value of an array.
    Reshape a 1D array of 12 elements into a 3x4 matrix.
Indexing and Masking
    Extract all elements greater than 5 from an array.
    Replace all negative numbers in an array with 0 using boolean indexing.
    Slice a 5x5 array to extract a 3x3 center block."""

In [3]:
import numpy as np

In [12]:
array=np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
zeros_array=np.zeros((3,3),int)
print(zeros_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
ones_array=np.ones((3,3),int)
print(ones_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [27]:
identitiy_matrix=np.identity((3),int)
print(identitiy_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
"""
The assignment is to create a multi dimensional dictionary of students with a dictionary of subjects containing obtain marks.
1. Create a numpy array from the bove dictionary.
2. Find out wich student gets more marks in what subject.
3. Create a ranking sequence based on their marks."""

In [5]:
student_data={"st-1":{"Maths":80, "Urdu":70, "Sindhi":40, "Chemistry":50, "Physics":60},
              "st-2":{"Maths":70, "Urdu":60, "Sindhi":30, "Chemistry":80, "Physics":90},
              "st-3":{"Maths":85, "Urdu":70, "Sindhi":40, "Chemistry":80, "Physics":60},
             }

student_ids=np.array([key for key in student_data.keys()])
subjects=np.array([list(key.keys()) for key in student_data.values()])[0]
marks=np.array([list(value.values()) for value in student_data.values()])

total_marks=marks.sum(axis=1)
ranking=sorted(enumerate(total_marks),key=lambda x:x[1], reverse=True)

for rank, (index,total) in enumerate(ranking):
    highest_subject_index=np.argmax(marks[index])
    print("**********")
    print(f"Rank:{rank}")
    print(f"Student Id: {student_ids[index]}")
    print(f"Subject with high score: {subjects[highest_subject_index]}")
    print(f"Score: {marks[index][highest_subject_index]}")
    print("**********")

**********
Rank:0
Student Id: st-3
Subject with high score: Maths
Score: 85
**********
**********
Rank:1
Student Id: st-2
Subject with high score: Physics
Score: 90
**********
**********
Rank:2
Student Id: st-1
Subject with high score: Maths
Score: 80
**********


In [5]:
student_data={"st-1":{"Maths":80, "Urdu":70, "Sindhi":40, "Chemistry":90, "Physics":60},
              "st-2":{"Maths":80, "Urdu":70, "Sindhi":40, "Chemistry":90, "Physics":60},
              "st-3":{"Maths":80, "Urdu":70, "Sindhi":95, "Chemistry":90, "Physics":60},
              "st-4":{"Maths":80, "Urdu":70, "Sindhi":40, "Chemistry":90, "Physics":60},
              "st-5":{"Maths":80, "Urdu":70, "Sindhi":40, "Chemistry":90, "Physics":60},
             }

student_ids=np.array([key for key in student_data.keys()])
student_array=np.array([list(std.values()) for std in student_data.values()])
subjects=np.array([list(key.keys()) for key in student_data.values()])[0]


print(student_ids)
print(student_array)
print(subjects)

# total_marks=marks.sum(axis=1)

# high_score=np.argmax(student_array,axis=1)
# print(high_score)
# high_score=np.array([int(student_array[index,value]) for index,value in enumerate(high_score)])
# print(high_score)
# top_students=np.argsort(-high_score)
# print(top_students)


# Ranking by total sum of marks

total_marks=np.sum(student_array,axis=1)
print(total_marks)
top_students=np.argsort(-total_marks)
print(top_students)

for rank,location in enumerate(top_students):
    print(f"Rank:{rank+1}\nStudent ID: {student_ids[location]}\nHigh Score: {total_marks[location]}")
    for subject, marks in zip(subjects,student_array[location]):  #zip function merges two lists and provide one by one values stored in it.
        print(f"{subject}: {marks}")

print(subjects)
print(student_array)
# for rank in top_students:

#     h_score=high_score[rank]
#     print("*"*10)
#     print(f"Rank:{np.where(top_students==rank)[0][0]+1}\nStudent ID: {student_ids[rank]}\nSubject with High score: {subjects[h_score]} Score:{student_array[rank,h_score]}")


['st-1' 'st-2' 'st-3' 'st-4' 'st-5']
[[80 70 40 90 60]
 [80 70 40 90 60]
 [80 70 95 90 60]
 [80 70 40 90 60]
 [80 70 40 90 60]]
['Maths' 'Urdu' 'Sindhi' 'Chemistry' 'Physics']
[340 340 395 340 340]
[2 0 1 3 4]
Rank:1
Student ID: st-3
High Score: 395
Maths: 80
Urdu: 70
Sindhi: 95
Chemistry: 90
Physics: 60
Rank:2
Student ID: st-1
High Score: 340
Maths: 80
Urdu: 70
Sindhi: 40
Chemistry: 90
Physics: 60
Rank:3
Student ID: st-2
High Score: 340
Maths: 80
Urdu: 70
Sindhi: 40
Chemistry: 90
Physics: 60
Rank:4
Student ID: st-4
High Score: 340
Maths: 80
Urdu: 70
Sindhi: 40
Chemistry: 90
Physics: 60
Rank:5
Student ID: st-5
High Score: 340
Maths: 80
Urdu: 70
Sindhi: 40
Chemistry: 90
Physics: 60
['Maths' 'Urdu' 'Sindhi' 'Chemistry' 'Physics']
[[80 70 40 90 60]
 [80 70 40 90 60]
 [80 70 95 90 60]
 [80 70 40 90 60]
 [80 70 40 90 60]]
