In [1]:
import numpy as np

In [ ]:
# insert(array, index, value, axis=None)
# array - original array
# index - position number
# value - data
# axis - None (faltten-array), 0 (row-wise), 1(column-wise).

In [50]:
array = np.array([10,20,30,40,50,60])
new_array = np.insert(array,2,100)

In [6]:
print(array)
print(new_array)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [14]:
arr_2d = np.array([[1,2],[3,4]])
new_arr = np.insert(arr_2d,2,[5,6],axis=1)  #axis = 1 (column-wise)

In [15]:
print(new_arr)

[[1 2 5]
 [3 4 6]]


In [16]:
arr_2d = np.array([[1,2],[3,4]])
new_arr = np.insert(arr_2d,2,[5,6],axis=0)  #axis = 1 (row-wise)

In [17]:
print(new_arr)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
arr_2d = np.array([[1,2],[3,4]])
new_arr = np.insert(arr_2d,2,[5,6],axis=None)  #axis = None (flatten array)

In [19]:
print(new_arr)

[1 2 5 6 3 4]


In [20]:
# append(): inserts elements at the end of an array

In [24]:
arr = np.array([10,20,30])
newArray = np.append(arr,[40,50,60])

In [25]:
print(newArray)

[10 20 30 40 50 60]


In [26]:
# concatenate((array_1,array_2),axis): to join the arrays together (returns tuple as a result)
# axis = 0    - Vertical stack (row-wise)      Note: To join arrays vertically their no.of columns must be same/equal.
# axis = 1    - Horizontal stack (column-wise) Note: To join arrays horizontally their no.of rows must be same/equal.
# axis = None - Flatten

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr2 = np.concatenate((arr1,arr2))

In [29]:
print(new_arr2)

[1 2 3 4 5 6]


In [34]:
new_arr3 = np.concatenate((arr1,arr2),axis=0)
print(new_arr3)

[1 2 3 4 5 6]


In [41]:
arr3 = np.array([[1,2,3],
                 [4,5,6]])
arr4 = np.array([[7,8,9],
                 [0,2,1]])

In [46]:
new_arr3 = np.concatenate((arr3,arr4),axis=1)  #Join arr4 after to the arr3 and column-wise

In [47]:
print(new_arr3)

[[1 2 3 7 8 9]
 [4 5 6 0 2 1]]


In [48]:
new_arr4 = np.concatenate((arr3,arr4))

In [49]:
print(new_arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 2 1]]


In [51]:
# delete(array, index, axis=None): deletes the particular element from an array 

In [52]:
ar = np.array([10,20,30,40,50,60])
print(ar)

[10 20 30 40 50 60]


In [54]:
del_arr = np.delete(ar,3)

In [55]:
print(del_arr)

[10 20 30 50 60]


In [61]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

In [60]:
print(A)

[[1 2]
 [3 4]]


In [62]:
print(B)

[[5 6]
 [7 8]]


In [65]:
C = np.hstack((A,B))  #Joins elements as side-by-side (horizontally): Requirement: No.of rows must be same

In [66]:
print(C)

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
D = np.vstack((A,B))  #Joins as one element is on top of other (vertically) : Requirement: No.of columns must be same

In [68]:
print(D)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [83]:
employee_ids = [[101],
                [102],
                [103],
                [104],
                [105]]


employee_salaries = [[2000],
                     [3000],
                     [4000],
                     [5000],
                     [6000]]

result = np.hstack((employee_ids, employee_salaries))

In [84]:
print(result)

[[ 101 2000]
 [ 102 3000]
 [ 103 4000]
 [ 104 5000]
 [ 105 6000]]


In [81]:
# Adding new-employee to the list of result using a vstack()
new_employee_id = [[106]]
new_employee_salary = [[7000]]
new_employee = np.hstack((new_employee_id, new_employee_salary))

result = np.vstack((result,new_employee))

In [82]:
print(result)

[[ 101 2000]
 [ 102 3000]
 [ 103 4000]
 [ 104 5000]
 [ 105 6000]
 [ 106 7000]
 [ 106 7000]]
