In [74]:
import numpy as np

In [75]:
array = np.array([1,2,3,4,5,6,7,8,9,10])

In [76]:
# Syntax for slicing operation: identifier[start_index, end_index-1, steps]

In [77]:
print(array[2:4])

[3 4]


In [78]:
print(array[:8]) #starts from zero till to the specified index

[1 2 3 4 5 6 7 8]


In [79]:
print(array[::]) #starts from zero till to the end

[ 1  2  3  4  5  6  7  8  9 10]


In [80]:
print(array[::2]) #prints every second element of an array

[1 3 5 7 9]


In [81]:
print(array[::-1]) #prints complete array in a reverse order

[10  9  8  7  6  5  4  3  2  1]


In [82]:
print(array[-1])  #prints the last element of an array

10


### Slicing of 2-D arrays

In [83]:
array_2d = np.array([[1,2,3,4,5],
                     [6,7,8,9,10]])

print(array_2d[1,1:4])  #[row_num,element_slicing]

[7 8 9]


In [84]:
print(array_2d[0:2,::2])  #prints 2nd element from each array inside the one large 2-D array

[[ 1  3  5]
 [ 6  8 10]]


In [85]:
print(array_2d[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [86]:
array_2d = np.array([[1,2,3,4,5],
                     [9,8,5,6,3],
                     [6,7,8,9,0]])
print(array_2d[0:3,2])

[3 5 8]


### Fancy indexing: Selecing multiple elements at once (instead of one by one).

In [87]:
print(array[[1,9,3]])  #prints the elements available at the specified indices

[ 2 10  4]


### Boolean Masking: Pick elements from an array based on certain condition (Machine learning usage)

In [88]:
print(array[array>5]) #prints the elements that are greather than the five 

[ 6  7  8  9 10]


In [89]:
evens = array[array%2==0]

In [90]:
print(f"Even elements are: {evens}")

Even elements are: [ 2  4  6  8 10]


In [91]:
odds = array[array%2!=0]

In [92]:
print(f"Odd elements are: {odds}")

Odd elements are: [1 3 5 7 9]


In [93]:
negative_ones = array[array%2==0]= -1

In [94]:
print(array[array==-1])   #print all the -1 elements stored in the array

[-1 -1 -1 -1 -1]


In [95]:
print(array)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [96]:
indices = np.where(array==-1)[0]

In [97]:
print(f"Indices of -1 elements stored in array: {indices}")

Indices of -1 elements stored in array: [1 3 5 7 9]


In [98]:
indices_2 = [index for index, value in enumerate(array) if value == -1]

In [99]:
print(f"Indices of -1 elements stored in array: {indices_2}")

Indices of -1 elements stored in array: [1, 3, 5, 7, 9]


In [100]:
# numbers = [1,2,3,4,5]
# print(numbers)

In [101]:
# numbers = numbers+22 #These operations couldn't work with lists directly, rather they only work with arrays

In [102]:
print(array+2)

[ 3  1  5  1  7  1  9  1 11  1]


In [103]:
print(array-2)

[-1 -3  1 -3  3 -3  5 -3  7 -3]


In [104]:
print(array*2)

[ 2 -2  6 -2 10 -2 14 -2 18 -2]


In [105]:
print(array/2)

[ 0.5 -0.5  1.5 -0.5  2.5 -0.5  3.5 -0.5  4.5 -0.5]


In [106]:
print(array**2)

[ 1  1  9  1 25  1 49  1 81  1]


In [107]:
print(array//2)

[ 0 -1  1 -1  2 -1  3 -1  4 -1]
