In [53]:
import numpy as np

In [54]:
array_1 = np.array([1,2,3,4,5])  #passing list to the array function

In [55]:
print(array_1)
print(type(array_1))   # ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [56]:
array_2 = np.array((1,2,3,4,5))  #passing tuple to the array function

In [57]:
print(array_2)
print(type(array_2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [58]:
#Creating 0_d array
x = np.array(2)  #0-d array np list or tuple specified just value passed to array() function
print(x)

2


In [59]:
print(f"Number of dimension: {x.ndim}") #to check the dimension of array

Number of dimension: 0


In [60]:
# Creating 1-D array
array_1d = np.array([1,2,3,4,5,6])
print(array_1d)

[1 2 3 4 5 6]


In [61]:
print(f"Number of dimensions: {array_1d.ndim}")

Number of dimensions: 1


In [62]:
# Creating 2-D array
array_2d = np.array([[1,2,3],[4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [63]:
print(f"Number of dimensions: {array_2d.ndim}")

Number of dimensions: 2


In [64]:
# Creating 3-D array
array_3d = np.array([
                    [[1,2,3],[4,5,6]],  #creating first   2-d
                    [[2,2,2],[3,3,3]]   #creating another 2-d
])
print(array_3d)

[[[1 2 3]
  [4 5 6]]

 [[2 2 2]
  [3 3 3]]]


In [65]:
print(f"Number of dimensions: {array_3d.ndim}")

Number of dimensions: 3


In [66]:
# Creating 5-D array
array_5d = np.array([1,2,3,4,5],ndmin=5)
print(array_5d)
print(f"Number of dimensions: {array_5d.ndim}")

[[[[[1 2 3 4 5]]]]]
Number of dimensions: 5
