In [1]:
import numpy as np

In [2]:
array= np.array([1,2,3,4,5])

In [3]:
new_array = array+2
new_array

array([3, 4, 5, 6, 7])

In [4]:
new_array2 = array-2
new_array2

array([-1,  0,  1,  2,  3])

In [5]:
new_array3 = array*2
new_array3

array([ 2,  4,  6,  8, 10])

In [6]:
new_array4 = array/4
new_array4

array([0.25, 0.5 , 0.75, 1.  , 1.25])