In [4]:
print("Hello")

Hello


## Hello, This is top heading
# Hi
SDNFDNFDF

# Hello, This is Heading
## This is sub-heading
### *It's Italic Now*
#### **It's Bold Now**
##### ***It's both Bold and Italic***
###### > Hello
`Hi`, Iam Ahsan Ali


In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
my_list=[[1,2,3,4],[3,4,5,6]]
print(my_list)
print(type(my_list))

[[1, 2, 3, 4], [3, 4, 5, 6]]
<class 'list'>


# Starting with Numpy

In [26]:
import numpy as np
my_array=[[1,2,3,4],[3,4,5,6]]
my_array=np.array(my_array)
print(my_array)
print(type(my_array))
print(np.ndim(my_array)) # Tells the number of dimensions of our array

[[1 2 3 4]
 [3 4 5 6]]
<class 'numpy.ndarray'>
2


In [22]:
import numpy as np
my_array=np.ndarray([1,2,3,4])
my_array

array([[[[1.17655750e-311, 1.17655857e-311, 1.17655857e-311,
          1.17655857e-311],
         [1.17655857e-311, 1.17655857e-311, 1.17655857e-311,
          1.17655857e-311],
         [1.17655857e-311, 1.17655857e-311, 1.17655857e-311,
          1.17655857e-311]],

        [[1.17655857e-311, 1.17655857e-311, 1.17655857e-311,
          1.17655857e-311],
         [1.17655857e-311, 1.17655857e-311, 1.17655857e-311,
          1.17655857e-311],
         [1.17655857e-311, 1.17655857e-311, 1.17655857e-311,
          1.17655857e-311]]]])

In [25]:
array=np.array([2,3,4,5,"a"])
array

array(['2', '3', '4', '5', 'a'], dtype='<U11')

# Numpy Functions

In [46]:
my_array=np.array([
    [[1,2],[2,3],[4,5]],
    [[6,7],[9,10],[11,12]]
])*2
print(my_array)
print(np.ndim(my_array))
print(np.shape(my_array))
print("Rows:",np.shape(my_array)[0],"Columns:",np.shape(my_array)[1])
# print(np.reshape(my_array))

[[[ 2  4]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [18 20]
  [22 24]]]
3
(2, 3, 2)
Rows: 2 Columns: 3


In [51]:
array=[[1,2,3],[4,5,6],[7,8,9]]

numbers=np.arange(10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
array=np.arange(50).reshape(10,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [73]:
numbers=np.arange(0,200,10).reshape(4,5)
numbers
print(array[4,1])
print(array[4:])
print(array[0:3])

21
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [74]:
print(array[3:,:3])  #(elements in complete row, total number of rows)

[[15 16 17]
 [20 21 22]
 [25 26 27]
 [30 31 32]
 [35 36 37]
 [40 41 42]
 [45 46 47]]


In [65]:
type(numbers)

numpy.ndarray

In [67]:
numbers.dtype   #used to detect/know the type of data stored in a particular column

dtype('int32')

In [85]:
nums=np.arange(0,100,10).reshape(5,2)
nums

array([[ 0, 10],
       [20, 30],
       [40, 50],
       [60, 70],
       [80, 90]])

In [83]:
print(nums[3:,:3])

[[60 70]
 [80 90]]


In [91]:
zeros_array=np.zeros((3,6),int)  # by default float
zeros_array

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [93]:
zeros_array.dtype

dtype('int32')

In [98]:
ones_array=np.ones((3,4),int)
ones_array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [103]:
array=np.array([2,3,4,5,6],dtype=float)
print(array)
array.dtype

[2. 3. 4. 5. 6.]


dtype('float64')