In [1]:
import numpy as np
from numpy import random

### linspace
#### Used to give values between two integers in a fixed range including decimals.

In [2]:
print(np.linspace(1,2,10))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


### Unique Elements

In [4]:
numbers_list=[2,3,4,5,6,8,8,8,9]
numbers_array=np.array(numbers_list)
print(numbers_array)
print(np.unique(numbers_array))

[2 3 4 5 6 8 8 8 9]
[2 3 4 5 6 8 9]


### Reshaping arrays

In [5]:
matrix=np.random.randint(0,10,size=(10,10))
print(matrix)
print("=====================================")
print(matrix.reshape(2,2,25)) #reshape() temporary provides view of our array not permanenly changes it

[[1 6 0 4 2 7 7 2 5 7]
 [2 7 3 3 5 2 9 5 7 4]
 [5 3 4 2 3 9 2 3 2 1]
 [5 3 4 0 4 8 7 4 4 6]
 [9 8 3 8 9 8 9 2 7 2]
 [8 5 5 8 9 7 5 9 4 8]
 [1 6 0 1 0 6 9 9 9 2]
 [4 7 4 2 9 2 1 9 0 3]
 [9 0 1 3 5 5 4 1 8 1]
 [5 6 1 6 7 2 1 4 6 5]]
[[[1 6 0 4 2 7 7 2 5 7 2 7 3 3 5 2 9 5 7 4 5 3 4 2 3]
  [9 2 3 2 1 5 3 4 0 4 8 7 4 4 6 9 8 3 8 9 8 9 2 7 2]]

 [[8 5 5 8 9 7 5 9 4 8 1 6 0 1 0 6 9 9 9 2 4 7 4 2 9]
  [2 1 9 0 3 9 0 1 3 5 5 4 1 8 1 5 6 1 6 7 2 1 4 6 5]]]


In [6]:
matrix.resize(4,25) #Changes the actual array
matrix

array([[1, 6, 0, 4, 2, 7, 7, 2, 5, 7, 2, 7, 3, 3, 5, 2, 9, 5, 7, 4, 5, 3,
        4, 2, 3],
       [9, 2, 3, 2, 1, 5, 3, 4, 0, 4, 8, 7, 4, 4, 6, 9, 8, 3, 8, 9, 8, 9,
        2, 7, 2],
       [8, 5, 5, 8, 9, 7, 5, 9, 4, 8, 1, 6, 0, 1, 0, 6, 9, 9, 9, 2, 4, 7,
        4, 2, 9],
       [2, 1, 9, 0, 3, 9, 0, 1, 3, 5, 5, 4, 1, 8, 1, 5, 6, 1, 6, 7, 2, 1,
        4, 6, 5]])

### Stacking and splitting

In [8]:
array_1=np.random.randint(0,10,size=(4,5))
print("array-1: ",array_1)

array_2=np.random.randint(0,10,size=(4,5))
print("array-2: ",array_2)

np.vstack((array_1,array_2))   # vertically stacks (No.of columns matters here i.e should be same)
np.hstack((array_1,array_2))   # horizontally stacks (No.of rows matters)

# np.delete(array_name, index of row/column,axis) # axis=0 (for row) and axis=1 (for column)

#np.column_stack(array_1,array_2) does stacking column wise but performs column wise not vertical axis wise (same as hstack)
#np.row_stack(array_1,array_2) does stacking row wise but performs row wise not horizontal axis wise  (same as vstack)
print("=====")
print(np.hsplit(array_1,(3,3)))

array-1:  [[1 5 3 1 5]
 [6 1 1 7 3]
 [0 5 4 9 9]
 [7 5 5 4 0]]
array-2:  [[3 4 6 1 2]
 [9 3 9 8 4]
 [2 2 8 4 5]
 [0 7 6 6 1]]
=====
[array([[1, 5, 3],
       [6, 1, 1],
       [0, 5, 4],
       [7, 5, 5]]), array([], shape=(4, 0), dtype=int32), array([[1, 5],
       [7, 3],
       [9, 9],
       [4, 0]])]


### Mathametical Operations

In [9]:
arr_1=np.array([1,2,3,4])
arr_2=np.array([2,4,5,6])

print(arr_1+arr_2)
# print(arr_1-arr_2)
# print(arr_1*arr_2)
# print(arr_1/arr_2)
# print(arr_1%arr_2)

#To choose the random number from the array
print(random.choice(arr_1))  

#To sum all the elements of array
print(arr_1.sum())  # returns sum of all the elements present in the array

arr_3=random.randint(100,size=(3,3))
print(arr_3)

print(arr_3.cumsum(axis=0))  # does sum row or column wise (add's the elements one by one from row/colum) axis=1 (for columns)

arr_3.min()
arr_3.max()

np.argmax(arr_3)  # returns index of largest number present in the array

np.add(arr_1,arr_2)  # adds elements of both arr_1 and arr_3
np.add(arr_1,2)  # adds value:2 to the all elements of arr_1
np.cbrt(arr_1) # for cube root

[ 3  6  8 10]
4
10
[[31 24 95]
 [16 55 39]
 [86 23 97]]
[[ 31  24  95]
 [ 47  79 134]
 [133 102 231]]


array([1.        , 1.25992105, 1.44224957, 1.58740105])

In [10]:
array=np.random.randint(0,9, size=(1,1))
array

array([[5]])