In [1]:
import numpy as np
# from numpy import * imports all the classes but don't requires alias for numpy
from numpy import random

In [2]:
numbers_list=[1,2,3,4,5,6,7,8,9,0,55,3,44,2,3,20,21,55]
print(numbers_list)
type(numbers_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 55, 3, 44, 2, 3, 20, 21, 55]


list

In [3]:
numbers_array=np.array(numbers_list)
numbers_array.dtype

dtype('int32')

### 2nd way to create numpy array

In [4]:
numbers=np.array([[[1,2,3],[2,4,5],[3,45,56]],[[4,77,56],[5,2,2],[6,4,5]],[[7,10,11],[8,20,40],[9,123,22]]])
print(numbers)
print("Shape of array: ",numbers.shape)
print("Dimensions of multi dimensional array: ",numbers.ndim)  #It's not a nested list rather it's a multi-dimensional array

[[[  1   2   3]
  [  2   4   5]
  [  3  45  56]]

 [[  4  77  56]
  [  5   2   2]
  [  6   4   5]]

 [[  7  10  11]
  [  8  20  40]
  [  9 123  22]]]
Shape of array:  (3, 3, 3)
Dimensions of multi dimensional array:  3


In [6]:
print("row1:",numbers.shape[0])
print("row2:",numbers.shape[1])
print("row3:",numbers.shape[2])

row1: 3
row2: 3
row3: 3


In [7]:
numbers_array.shape

(18,)

In [8]:
print(numbers_array.reshape(6,3))   #reshape(no.of rows, no.of columns)
print(numbers_array.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 55  3]
 [44  2  3]
 [20 21 55]]
1


In [9]:
nums=np.arange(1,100,2)
nums

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
np.zeros((2,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((2,2),int)

array([[1, 1],
       [1, 1]])

In [12]:
np.eye(4,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [13]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [14]:
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [15]:
np.dtype?

Init signature: np.dtype(self, /, *args, **kwargs)
Docstring:     
dtype(dtype, align=False, copy=False, [metadata])

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
dtype
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.
metadata : dict, optional
    An optional dictionary with dtype metadata.

See also
--------
result_type

Examples
--------
Using array-scalar type:



In [16]:
np.random.randint([50,100])

array([45, 78])

In [17]:
np.random.randint(-2,4)   #np.random.randint(number from which we start, upto the number --> (This number is not included))

1

In [19]:
np.random.randint(100 ,size=(10,2))  # np.random.randint(total_elements,size=(rows,columns))

array([[78, 98],
       [46, 62],
       [79, 51],
       [51, 86],
       [ 6, 17],
       [96, 36],
       [ 6, 13],
       [67, 26],
       [70, 77],
       [37, 44]])

In [20]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [21]:
np.random.randint(50,100,size = (5,5))   #prints elements between 50-100 (50 & 100 not included) with 5 rows and 5 columns
# np.random.randint(low_range,high_range,size=(rows,columns))

array([[82, 76, 96, 74, 60],
       [77, 74, 79, 96, 79],
       [73, 54, 89, 90, 50],
       [53, 69, 65, 50, 89],
       [86, 51, 89, 84, 66]])

In [22]:
np.random.randint([3,5,9])

array([0, 3, 1])

In [23]:
array2=np.random.randint(50,100,size=(5,5))
print(array2)

[[52 90 71 59 77]
 [97 59 88 98 76]
 [90 57 94 77 80]
 [69 50 89 68 83]
 [93 84 95 71 92]]


In [24]:
array2.flatten()  #converts all the rows into a single rows (row wise merging of numbers)

array([52, 90, 71, 59, 77, 97, 59, 88, 98, 76, 90, 57, 94, 77, 80, 69, 50,
       89, 68, 83, 93, 84, 95, 71, 92])

In [25]:
array2.flatten("F") # does the merging of numbers column wise

array([52, 97, 90, 69, 93, 90, 59, 57, 50, 84, 71, 88, 94, 89, 95, 59, 98,
       77, 68, 71, 77, 76, 80, 83, 92])

In [26]:
array2[0:3,2:4]  #[:no.of rows, starting column no, ending column no]

array([[71, 59],
       [88, 98],
       [94, 77]])

In [27]:
array2[2,4]  #same as array2[2][4] or array2[row][column] in numpy array2[row,column]

80

In [28]:
array2[0:2,0:4]

array([[52, 90, 71, 59],
       [97, 59, 88, 98]])

In [29]:
array2[0:2,2:5]

array([[71, 59, 77],
       [88, 98, 76]])

In [30]:
array2[array2%2==0]  #prints all the even numbers without any loop 

array([52, 90, 88, 98, 76, 90, 94, 80, 50, 68, 84, 92])

In [31]:
array2[(array2%2==0) & (array2>80)]

array([90, 88, 98, 90, 94, 84, 92])